### ISSUE TITLE
Organizing the React Files for Deployment to GitHub Pages

### ISSUE THREAD

**Issue by GillianTrethewey** [chingu-voyages/v44-tier2-team-26#15]
**__User Story Description__**
As a team, we want to be able to have our React project files setup on GitHub, so that we can host our final project on GitHub easily.

**__Steps to Follow__**
1. Research the file setup - https://www.youtube.com/watch?v=dalXCXCIPHM
2. Create the correct setup of files on our develop branch after populating pages with basic components.
4. Deploy it to gh-pages branch

**__Additional Considerations__**
The advantage of setting up on GitHub means that Chingu will host permanently. With an external provider such as Vercel or Netlify is that one individual has to host/maintain it and in the future this may require payment.

**Comment by rselvasoyak** [comment]
Very helpful video too learn about GitHub hosting - Also found this video as a second resource if anyone needs it as well: https://www.youtube.com/watch?v=QyFcl_Fba-k
