### ISSUE TITLE
Readme.md file

### ISSUE THREAD

**Issue by GillianTrethewey** [chingu-voyages/v44-tier2-team-26#19]
**__User Story Description__**
As a user
I want to read about the project and the contributors
So I can understand it and contact the team.

**__Steps to Follow__**
- [x] 1. Write a description of the project with full details. This is what people read to make sure they're cloning the right projects in the future.
- [x] 2. Include details on the Team Members - LinkedIn and GitHub profiles.
- [x] 3. Include details on the stack used along with icons for each tool/library/framework.
https://github.com/tandpfun/skill-icons
- [x] 4. Look at other good examples from the Chingu repo.
- [x] 5. Link to the GitHub.io page once we are live.

**__Additional Considerations__**
Screenshots of the final project will be included at the end.

Gillian Trethewey
LInkedIn: https://www.linkedin.com/in/gillian-trethewey/
GitHub: https://github.com/GillianTrethewey

Keith Petryshyn
LinkedIn: https://www.linkedin.com/in/keith-petryshyn-886b5016/
GitHub: https://github.com/KeithPetr

Lee Goullaud
LinkedIn: https://www.linkedin.com/in/lee-goullaud/
GitHub: https://github.com/egoullaud

Rana Selva Soyak
Linkedin: https://www.linkedin.com/in/ranasoyakcodes/
GitHub: https://github.com/rselvasoyak

**Comment by KeithPetr** [comment]
I have finished the basic layout for the Readme including what was asked of in the issue.
