### ISSUE TITLE
User Story: Leaderboard

### ISSUE THREAD

**Issue by GillianTrethewey** [chingu-voyages/v44-tier2-team-26#32]
- Leaderboard
    -   [ ] User can see the display of wins and losses for each bot on the
    leaderboard
    -   [ ] User can see the tally of wins incremented for bots winning a collision.
    -   [ ] User can see the tally of losses decremented for bots losing a collision.

**Comment by egoullaud** [comment]
- Leaderboard
    -   [ ] User can see the display of wins and losses for each bot on the
    leaderboard
    -   [ ] User can see the tally of wins incremented for bots winning a collision.
    -   [ ] User can see the tally of losses decremented for bots losing a collision.
